### ISSUE TITLE
How to make a Lamp Server so it matches the main site

### ISSUE THREAD

**Issue by Hawaiideveloper** [Hawaiideveloper/bluSky#3]
https://phoenixnap.com/kb/how-to-install-lamp-stack-on-ubuntu

**Comment by manzanarez83** [comment]
`#!/bin/bash 
​
​
​
​
sudo apt-get update -y  

sudo apt-get install apache2 -y  

sudo service apache2 status -y  
`

**Comment by manzanarez83** [comment]
Hey, I got tired of reading it over and over so I created a script to do it faster

https://github.com/Hawaiideveloper/bluSky/pull/4
