### ISSUE TITLE
Permission denied on '/var/www/html/

### ISSUE THREAD

**Issue by ervinj1998** [Hawaiideveloper/bluSky#5]
mv BluSky/* /var/www/html
mv: cannot move 'BluSky/blueSky.code-workspace' to '/var/www/html/blueSky.code-workspace': Permission denied
mv: cannot move 'BluSky/css' to '/var/www/html/css': Permission denied
mv: cannot move 'BluSky/Examples_Media_Usage' to '/var/www/html/Examples_Media_Usage': Permission denied
mv: cannot move 'BluSky/free_members_only' to '/var/www/html/free_members_only': Permission denied
mv: cannot move 'BluSky/images' to '/var/www/html/images': Permission denied
mv: replace '/var/www/html/index.html', overriding mode 0644 (rw-r--r--)?

**Comment by Hawaiideveloper** [comment]
You need to take ownership:
https://manpages.ubuntu.com/manpages/trusty/man1/chown.1.html


so type this:

```
sudo chown -R $USER /var/www/html
```


the $USER variable uses the person who is presently logged on.  Which is `you`

**Comment by Hawaiideveloper** [comment]
copy the above and paste it let me know if that works

**Comment by Hawaiideveloper** [comment]
# Solved

---


Glad it worked @ervinj1998

**Comment by Hawaiideveloper** [comment]
Now closing as solved
